### ISSUE TITLE
materialx/emoji.py wants to import material, but the potential dependency isn't listed in setup.py

### ISSUE THREAD

**Issue by tijuca** [facelessuser/mkdocs-material-extensions#18]
Hi,

while trying to improve the Debian packaging for mkdocs-material-extensions I want to get the tests working.
This fails currently as `materialx/emoji.py` is trying to import a module `material`.

```
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:240: cd /build/mkdocs-material-extensions-1.0.3/.pybuild/cpython3_3.10_materialx/build; python3.10 -m unittest discover -v 
tests.extensions.test_emoji (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests.extensions.test_emoji (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.extensions.test_emoji
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/mkdocs-material-extensions-1.0.3/.pybuild/cpython3_3.10_materialx/build/tests/extensions/test_emoji.py", line 3, in <module>
    from materialx import emoji
  File "/build/mkdocs-material-extensions-1.0.3/.pybuild/cpython3_3.10_materialx/build/materialx/emoji.py", line 11, in <module>
    import material
ModuleNotFoundError: No module named 'material'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

The `setup.py` file nor `requirements/project.txt` is holding any list of depending packages.

The only reference for a module named `material` I've found on PyPi is quite old. https://pypi.org/project/material/
But this looks not quite the correct one. If this the correct thing, is it really needed to include that old code with only a few lines of code, it was last touched in 2014? Couldn't get this included into the package itself somehow. Otherwise I would need to get this old stuff packaged for Debian and this isn't something I'd do with joy. :-/

**Comment by facelessuser** [comment]
Okay, I can understand why you are confused, but let me explain the situation.

I link to the actual associated package in the readme, it is https://github.com/squidfunk/mkdocs-material, which can  be found on PyPI as https://pypi.org/project/mkdocs-material/. Why does it install as `material` instead of `mkdocs_material` 🤷🏻 .

MkDocs Material is an extremely popular theme for MkDocs. The author had more experience as a front-end developer and, at the time, was very unfamiliar with Python. He wanted a way to utilize the Emoji extension from https://github.com/facelessuser/pymdown-extensions to reference the arbitrary icons included as data within the MkDocs Material package. This repo creates the necessary extension to do that, but MkDocs Material requires this package in its setup.

Originally, we did include the reference in our requirements to MkDocs Material as can be seen here: https://github.com/facelessuser/mkdocs-material-extensions/commit/5629ed56b491dc13ad1fc2b2c373792e3ab2107b#diff-cf146e3b26df09c0bdc0f5e2d384d15023cb825059a8cba17e8d6dfd985f32ec. The problem was that it created a circular reference in various package locking solutions.  Due to many requests to eliminate this issue, I finally caved and removed the circular reference.

In an Ideal world, MkDocs Material would absorb this extension into its package, but that has not happened yet.

**Comment by tijuca** [comment]
Ahh, o.k., thanks for an explanation, so I then tend to believe the packaging of `mkdocs-material` in Debian isn't correct. The package is not installed into the usual folder structure that end up in a availability of the module in the PYTHONPATH but into a folder `/usr/share/mkdocs/themes` currently. This seems not correct to me as importing the module `material` can't work that way.

I'll try to get in contact with the maintainer.

**Comment by facelessuser** [comment]
Well, keep in mind that it creates an entry point which is a requirement for the MkDocs plugin system, but the entry point is not where the extension is supposed to physically live.

```
[project.entry-points."mkdocs.themes"]
material = "material"
```

**Comment by facelessuser** [comment]
Okay, closing this as there are currently no actionable items and conversation seems to have stopped. Feel free to reopen if further conversation is required.
