### ISSUE TITLE
Icon set discovery broken on Poetry installations, due to unescaped glob path

### ISSUE THREAD

**Issue by hheimbuerger** [facelessuser/mkdocs-material-extensions#22]
I'm running mkdocs-material using Poetry and a Python 3.10 installation from the Windows Store.

In [emoji.py:43](https://github.com/facelessuser/mkdocs-material-extensions/blob/master/materialx/emoji.py#L43), there's the following expression:

    glob.glob(icon_path.replace('\\', '/') + '/**/*.svg', recursive=True)

[This doesn't yield any files for me.](https://github.com/squidfunk/mkdocs-material/discussions/4662) The issue is that Poetry generates square brackets in folder names, and these have significance for the `glob()`  function. For example:

`C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\[mkdocs]-yKbMSAs--py3.10\lib\site-packages\material\.icons` 

Therefore:

    >>> glob.glob(icon_path + '/**/*.svg', recursive=True)
    []

The cleanest solution I've found is to separate pattern from directory by using the `root_dir` argument:

    >>> glob.glob('**/*.svg', root_dir=icon_path, recursive=True)
    ['logo.svg', 'fontawesome\\brands\\42-group.svg', 'fontawesome\\brands\\500px.svg', ...

However, I believe that parameter was introduced in Python 3.10 and I think mkdocs-material specifies 3.7+ in its requirements.

So alternatively, there's [glob.escape()](https://docs.python.org/3.4/library/glob.html#glob.escape). This works:

    >>> glob.glob(glob.escape(icon_path) + '/**/*.svg', recursive=True)
    ['C:\\Users\\me\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Local\\pypoetry\\Cache\\virtualenvs\\[mkdocs]-yKbMSAs--py3.10\\lib\\site-packages\\material\\.icons\\logo.svg', ...

I'm not sure what the purpose of the `.replace('\\', '/')` call was, because the `glob` module has no issues with either backslashes or slashes on Windows in my tests. Was this an attempt of platform-independence? Either way, I would suggest not doing this manually, but using `pathlib` instead:

    >>> glob.glob(str(pathlib.Path(glob.escape(icon_path)) / '**' / '*.svg'), recursive=True)
    ['C:\\Users\\me\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Local\\pypoetry\\Cache\\virtualenvs\\[mkdocs]-yKbMSAs--py3.10\\lib\\site-packages\\material\\.icons\\logo.svg', ...

PS: Your [PyPI page](https://pypi.org/project/mkdocs-material-extensions/) has a broken Homepage link, it contains a superfluous apostrophe and links [here](https://github.com/facelessuser/mkdocs-material-extensions').

**Comment by facelessuser** [comment]
> PS: Your [PyPI page](https://pypi.org/project/mkdocs-material-extensions/) has a broken Homepage link, it contains a superfluous apostrophe and links [here](https://github.com/facelessuser/mkdocs-material-extensions').

Yes, this was already fixed on `master` a bit ago, it just isn't live on PyPI yet: https://github.com/facelessuser/mkdocs-material-extensions/commit/581e6b0371611ebd4f6d2a7506c2b62331ae06b4

> Was this an attempt of platform-independence?

Most people feed glob patterns into Python's glob with forward slashes. This is probably more due to the fact that manually typing a backslash path in Python is can be problematic as backslashes are escape characters. This probably isn't so much a problem when dealing with inputs that directly come from other places where problematic backslashes are already resolved. With that said, we are also doing other manipulations on the path and wanted a consistent expectation of the path, less for normalization of Python handling the paths in glob as much as we wanted to transform paths to certain paths to emoji names.

> The issue is that Poetry generates square brackets in folder names, and these have significance for the glob() function.

Yes, this is the real issue, and it is a problem with special chars. Unfortunately, this plugin was hastily put together, and the approach was naive in this sense. As someone who maintains their own [glob library](https://github.com/facelessuser/wcmatch), and is well aware of the significance of special characters, this was pretty dumb on my part, but such is life 🙂.

But yes, using something like `glob.escape` or `pathlib`'s `rglob` would be a reasonable solution.

**Comment by facelessuser** [comment]
I should be able to tag a release later today

**Comment by hheimbuerger** [comment]
> I should be able to tag a release later today

Awesome, cheers!

**Comment by hheimbuerger** [comment]
I've upgraded to version 1.1.1 from PyPI (via `poetry add mkdocs-material-extensions@1.1.1`) and the icons are now working fine for me! 👍
